const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Plugins.Mikal_3DObject,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.TextBox,
		C3.Plugins.NinePatch,
		C3.Behaviors.Flash,
		C3.Plugins.Timeline,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Json,
		C3.Plugins.GD_SDK,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.MoveToLayer,
		C3.Plugins.Mikal_3DObject.Cnds.OnCreated,
		C3.Plugins.Mikal_3DObject.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mikal_3DObject.Acts.LoadModel,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Mikal_3DObject.Exps.UID,
		C3.Plugins.Mikal_3DObject.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Mikal_3DObject.Acts.StopAnimation,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Plugins.Mikal_3DObject.Cnds.OnLoaded,
		C3.Plugins.Mikal_3DObject.Acts.SetStaticGeometry,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationSpeed,
		C3.Plugins.Mikal_3DObject.Acts.SetScale,
		C3.Plugins.Mikal_3DObject.Acts.LoadMaterialFromSprite,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Mikal_3DObject.Cnds.IsLoaded,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Mikal_3DObject.Acts.LoadModelFromTemplate,
		C3.Plugins.Mikal_3DObject.Cnds.CompareInstanceVar,
		C3.Plugins.Mikal_3DObject.Acts.SetX,
		C3.Plugins.Mikal_3DObject.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Mikal_3DObject.Cnds.CompareX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Mikal_3DObject.Cnds.PickByUID,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Mikal_3DObject.Cnds.IsOnScreen,
		C3.Plugins.Mikal_3DObject.Acts.SetRotationOrdered,
		C3.Plugins.Mikal_3DObject.Exps.YAngle,
		C3.Plugins.Mikal_3DObject.Exps.XAngle,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Mikal_3DObject.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.Mikal_3DObject.Acts.SetDefaultColor,
		C3.Plugins.Mikal_3DObject.Cnds.IsVisible,
		C3.Plugins.Mikal_3DObject.Exps.Y,
		C3.Plugins.Particles.Acts.SetZElevation,
		C3.Plugins.Mikal_3DObject.Exps.ZElevation,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Mikal_3DObject.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Acts.ToggleBoolInstanceVar,
		C3.Plugins.NinePatch.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Cnds.CompareX,
		C3.Plugins.Shape3D.Cnds.IsOnScreen,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Shape3D.Acts.SetY,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.ScriptsInEvents.Game_Event339_Act1,
		C3.Plugins.GD_SDK.Acts.ShowRewardedAd,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Shape3D.Cnds.OnDestroyed,
		C3.Plugins.Spritefont2.Cnds.CompareOpacity,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Timeline.Acts.StopAllTimelines,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.ScriptsInEvents.Game_Event383_Act51,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.SetZElevation,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Mikal_3DObject.Cnds.PickChildren,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Acts.SetSizeRandomiser,
		C3.Plugins.Particles.Cnds.IsOnScreen,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.ScriptsInEvents.Game_Event431_Act1,
		C3.ScriptsInEvents.Game_Event434_Act1,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Shape3D.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.GD_SDK.Cnds.PreloadedAd,
		C3.Plugins.GD_SDK.Acts.PreloadRewardedAd,
		C3.Plugins.GD_SDK.Cnds.PauseGame,
		C3.Plugins.GD_SDK.Cnds.ResumeGame,
		C3.Plugins.GD_SDK.Cnds.RewardPlayer,
		C3.ScriptsInEvents.Game_Event474_Act1,
		C3.Plugins.AdvancedRandom.Acts.SetSeed,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.ScriptsInEvents.Missionhandler_Event18,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Spritefont2.Exps.BBoxRight,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.ScriptsInEvents.Missionhandler_Event33_Act7,
		C3.Plugins.GD_SDK.Acts.ShowAd,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Shape3D.Cnds.CompareY,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.Mikal_3DObject.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Mikal_3DObject.Exps.ZAngle,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Mikal_3DObject.Acts.SetPosToObject,
		C3.ScriptsInEvents.Functions_Event14,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.RemoveJoints
	];
};
self.C3_JsPropNameTable = [
	{id: 0},
	{Physics: 0},
	{LeftWheel: 0},
	{RightWheel: 0},
	{up: 0},
	{auto: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{CarBody: 0},
	{Keyboard: 0},
	{antb: 0},
	{antm: 0},
	{antt: 0},
	{"3DCamera": 0},
	{temp_height: 0},
	{"3d_ground": 0},
	{char2_left_wheel: 0},
	{char2_body: 0},
	{char2_right_wheel: 0},
	{ground_top: 0},
	{block: 0},
	{block1_map: 0},
	{block2_map: 0},
	{base: 0},
	{shadow: 0},
	{sky: 0},
	{dead: 0},
	{Fade: 0},
	{Anchor: 0},
	{fader: 0},
	{trigger: 0},
	{Text: 0},
	{value: 0},
	{dummy: 0},
	{dull: 0},
	{Sine: 0},
	{fuel: 0},
	{money: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{pole1_map: 0},
	{pole2_map: 0},
	{toggle: 0},
	{Tween: 0},
	{bomb: 0},
	{spark: 0},
	{spark_map: 0},
	{ground_top2: 0},
	{number: 0},
	{difficulty: 0},
	{moneySpawnProbab: 0},
	{bombSpawnProbab: 0},
	{chunk: 0},
	{moneySpawnner: 0},
	{petrolSpawnner: 0},
	{AdvancedRandom: 0},
	{chunkEnd: 0},
	{bombSpawnner: 0},
	{TextInput: 0},
	{t_dist: 0},
	{ground_cover: 0},
	{Flash: 0},
	{fuel_meter: 0},
	{switcher: 0},
	{road_shadow: 0},
	{planet: 0},
	{r: 0},
	{g: 0},
	{b: 0},
	{state: 0},
	{color_texture: 0},
	{TimelineController: 0},
	{bg: 0},
	{blocker: 0},
	{money_ui: 0},
	{money_txt: 0},
	{fuel_bg: 0},
	{obstacle_tile1: 0},
	{pole4: 0},
	{pole4_map: 0},
	{pole4_map2: 0},
	{enable: 0},
	{obs_collision: 0},
	{obstacle_tile2: 0},
	{Pin: 0},
	{CarBody2: 0},
	{activate: 0},
	{Rotate: 0},
	{cash: 0},
	{Bullet: 0},
	{crash_block: 0},
	{pole_warning: 0},
	{Sine2: 0},
	{warning_sign: 0},
	{block2: 0},
	{board_map2: 0},
	{board_map1: 0},
	{billboard_txt: 0},
	{ground_top3: 0},
	{billboard: 0},
	{pole_warning2: 0},
	{score_txt: 0},
	{best_txt: 0},
	{anim: 0},
	{flip_txt: 0},
	{money_ui2: 0},
	{fuel_text: 0},
	{landing_part1_map: 0},
	{gas_info: 0},
	{left_touch: 0},
	{right_touch: 0},
	{jump_touch: 0},
	{Touch: 0},
	{fullscreen: 0},
	{block3: 0},
	{init: 0},
	{camera_control: 0},
	{title: 0},
	{syderstudio_logo: 0},
	{billboard2: 0},
	{car_stopper: 0},
	{right_key: 0},
	{garage: 0},
	{blocker_menu: 0},
	{TiledBackground: 0},
	{rotate: 0},
	{dummy2: 0},
	{trigger2: 0},
	{tut_touch: 0},
	{Jump_info: 0},
	{engine_upgrade: 0},
	{block4: 0},
	{body_upgrade: 0},
	{wheel_upgrade: 0},
	{fuel_upgrade: 0},
	{strength_upgrade: 0},
	{garage_bg: 0},
	{garage_ui_icon: 0},
	{garage_title: 0},
	{garage_item_info: 0},
	{money_ui3: 0},
	{money_txt_garage: 0},
	{buy: 0},
	{AJAX: 0},
	{missionArray: 0},
	{missionText: 0},
	{missionStatus: 0},
	{char1_body: 0},
	{char1_right_wheel: 0},
	{char1_left_wheel: 0},
	{char3_body: 0},
	{char3_left_wheel: 0},
	{char3_right_wheel: 0},
	{change_skin: 0},
	{prev: 0},
	{next: 0},
	{menu_blocker: 0},
	{char4_right_wheel: 0},
	{char4_left_wheel: 0},
	{char4_body: 0},
	{char5_body: 0},
	{char5_right_wheel: 0},
	{char5_left_wheel: 0},
	{mission_bg: 0},
	{mission_txt_UI: 0},
	{missionIndex: 0},
	{check: 0},
	{toggler: 0},
	{mission_txt_UI2: 0},
	{money_ui4: 0},
	{mission_complete: 0},
	{char6_right_wheel: 0},
	{char6_body: 0},
	{char6_left_wheel: 0},
	{missionCompleteArray: 0},
	{pause: 0},
	{pause_bg1: 0},
	{active: 0},
	{pause_bg_a: 0},
	{continue: 0},
	{exit: 0},
	{about: 0},
	{about_txt: 0},
	{close: 0},
	{frame: 0},
	{crashed_bg: 0},
	{final_money: 0},
	{garage_btn: 0},
	{money_ui5: 0},
	{score_txt_crashed: 0},
	{pause_bg2: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{about2: 0},
	{char_body: 0},
	{garage_text: 0},
	{garage_yellow_neon: 0},
	{garage_blue_neon: 0},
	{block6: 0},
	{garage_spark: 0},
	{building3d: 0},
	{bg_black: 0},
	{side_road_texture: 0},
	{fps_counter: 0},
	{vignetteanimation: 0},
	{speed: 0},
	{f_car: 0},
	{"3d_jet": 0},
	{jet_part: 0},
	{stars_sky: 0},
	{newspaper: 0},
	{drone3d: 0},
	{block_side: 0},
	{billboard_txt_ins: 0},
	{building_texture: 0},
	{char7_body: 0},
	{char7_left_wheel: 0},
	{char7_right_wheel: 0},
	{char8_body: 0},
	{char8_left_wheel: 0},
	{char8_right_wheel: 0},
	{char11_body: 0},
	{char11_left_wheel: 0},
	{char11_right_wheel: 0},
	{char12_body: 0},
	{char12_left_wheel: 0},
	{char12_right_wheel: 0},
	{lock_unlock_btn: 0},
	{VehicleCost: 0},
	{jet_texture: 0},
	{"3d_jet2": 0},
	{board_3d: 0},
	{pole4_map3: 0},
	{car1_texture: 0},
	{car2_texture: 0},
	{car3_texture: 0},
	{car4_texture: 0},
	{car5_texture: 0},
	{car6_texture: 0},
	{car7_texture: 0},
	{upgrade_json: 0},
	{car8_texture: 0},
	{car9_texture: 0},
	{fog_txt: 0},
	{glow_btn: 0},
	{fog_btn: 0},
	{title2: 0},
	{mission_bg_patch: 0},
	{seque: 0},
	{attribution_txt: 0},
	{resolution_txt: 0},
	{resolution_btn: 0},
	{info_op_txt: 0},
	{tutorial_txt: 0},
	{rotate_info: 0},
	{bomb_gas: 0},
	{control_enable: 0},
	{GameDistributionSDK: 0},
	{Family1: 0},
	{wheel: 0},
	{buttons: 0},
	{upgrades: 0},
	{carBody3D: 0},
	{carWheel3D: 0},
	{MaxSpeed: 0},
	{Speed: 0},
	{Acel: 0},
	{DeAcel: 0},
	{control: 0},
	{Character: 0},
	{car_model_name: 0},
	{wheel_model_name: 0},
	{Frame_rate: 0},
	{distanceCovered: 0},
	{water_z_elevation: 0},
	{water_toggle: 0},
	{water_offset_value: 0},
	{fuel_meter_value: 0},
	{level_toggle: 0},
	{end: 0},
	{temp_distance: 0},
	{layout_counter: 0},
	{cloud_color_r: 0},
	{cloud_color_g: 0},
	{cloud_color_b: 0},
	{planet_toggle: 0},
	{money_counter: 0},
	{distance_2: 0},
	{distance_value: 0},
	{best: 0},
	{left_flip: 0},
	{right_flip: 0},
	{left_trigger: 0},
	{top_trigger: 0},
	{right_trigger: 0},
	{buttom_trigger: 0},
	{direction: 0},
	{temp_rightflip: 0},
	{temp_leftflip: 0},
	{semophore: 0},
	{extra_boost: 0},
	{temp_angle: 0},
	{temp_y: 0},
	{time_checker: 0},
	{menu: 0},
	{sequence: 0},
	{tutorial: 0},
	{engine: 0},
	{body: 0},
	{wheels: 0},
	{gas: 0},
	{strength: 0},
	{fuel_rate: 0},
	{density: 0},
	{impulse_value: 0},
	{jump_strength: 0},
	{rotate_value: 0},
	{pressed: 0},
	{pause_visible: 0},
	{pause_UI_show: 0},
	{purchasing_value: 0},
	{prefab_uid_jet: 0},
	{LockedState: 0},
	{upgradeState: 0},
	{PokiSdkLoaded: 0},
	{PokiSdkInitialized: 0},
	{initialGameplayStart: 0},
	{isAdPlaying: 0},
	{freeMoneyCount: 0},
	{baseCharacterCost: 0},
	{rewardedAdCharacterCostMultiplier: 0},
	{rewardedCarUnlock: 0},
	{prefab_jet2: 0},
	{jump_enable: 0},
	{camera_static: 0},
	{numberOfChunks: 0},
	{selectedChunk: 0},
	{destroyDist: 0},
	{spawnNewChunkDist: 0},
	{carInitialX: 0},
	{chunkNumber: 0},
	{petrolSpawnChunkSeparation: 0},
	{maxLevelDist: 0},
	{currentMission: 0},
	{rightFlipCount: 0},
	{leftFlipCount: 0},
	{moneyCount: 0},
	{fuelCount: 0},
	{landingCount: 0},
	{fenceCount: 0},
	{bombCount: 0},
	{jumpCount: 0},
	{crashCount: 0},
	{avoidanceThreshold: 0},
	{missionComplete: 0},
	{crashed_money: 0},
	{reward_purpose: 0},
	{average_fps: 0},
	{automatic: 0},
	{glow_enable: 0},
	{fog_enable: 0},
	{resolution: 0},
	{first_launch: 0},
	{sound: 0},
	{focus: 0},
	{characterID: 0},
	{RWFrontZElevation: 0},
	{RWBackZElevation: 0},
	{LWFrontZElevation: 0},
	{LWBackZElevation: 0},
	{Animation: 0},
	{destroyImpulse: 0},
	{LWSizeX: 0},
	{LWSizeY: 0},
	{RWSizeX: 0},
	{RWSizeY: 0},
	{decreaseCarDensity: 0},
	{RWDensity: 0},
	{LWDensity: 0}
];

self.InstanceType = {
	LeftWheel: class extends self.ISpriteInstance {},
	RightWheel: class extends self.ISpriteInstance {},
	CarBody: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	antb: class extends self.ISpriteInstance {},
	antm: class extends self.ISpriteInstance {},
	antt: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	_3d_ground: class extends self.I3DShapeInstance {},
	char2_left_wheel: class extends self.IWorldInstance {},
	char2_body: class extends self.IWorldInstance {},
	char2_right_wheel: class extends self.IWorldInstance {},
	ground_top: class extends self.ITiledBackgroundInstance {},
	block: class extends self.I3DShapeInstance {},
	block1_map: class extends self.ITiledBackgroundInstance {},
	block2_map: class extends self.ITiledBackgroundInstance {},
	base: class extends self.ITiledBackgroundInstance {},
	shadow: class extends self.ISpriteInstance {},
	sky: class extends self.ITiledBackgroundInstance {},
	dead: class extends self.ISpriteInstance {},
	fader: class extends self.ITiledBackgroundInstance {},
	trigger: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	dummy: class extends self.ITiledBackgroundInstance {},
	dull: class extends self.ISpriteInstance {},
	fuel: class extends self.IWorldInstance {},
	money: class extends self.IWorldInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	pole1_map: class extends self.ITiledBackgroundInstance {},
	pole2_map: class extends self.ITiledBackgroundInstance {},
	bomb: class extends self.IWorldInstance {},
	spark: class extends self.IParticlesInstance {},
	spark_map: class extends self.ISpriteInstance {},
	ground_top2: class extends self.ITiledBackgroundInstance {},
	chunk: class extends self.ISpriteInstance {},
	moneySpawnner: class extends self.ISpriteInstance {},
	petrolSpawnner: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	chunkEnd: class extends self.ISpriteInstance {},
	bombSpawnner: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	t_dist: class extends self.ITextInstance {},
	ground_cover: class extends self.ITiledBackgroundInstance {},
	fuel_meter: class extends self.IWorldInstance {},
	switcher: class extends self.ISpriteInstance {},
	road_shadow: class extends self.ITiledBackgroundInstance {},
	planet: class extends self.ISpriteInstance {},
	color_texture: class extends self.ITiledBackgroundInstance {},
	TimelineController: class extends self.IInstance {},
	bg: class extends self.ITiledBackgroundInstance {},
	blocker: class extends self.ISpriteInstance {},
	money_ui: class extends self.ISpriteInstance {},
	money_txt: class extends self.ISpriteFontInstance {},
	fuel_bg: class extends self.ISpriteInstance {},
	obstacle_tile1: class extends self.ITiledBackgroundInstance {},
	pole4: class extends self.I3DShapeInstance {},
	pole4_map: class extends self.ITiledBackgroundInstance {},
	pole4_map2: class extends self.ITiledBackgroundInstance {},
	obs_collision: class extends self.ISpriteInstance {},
	obstacle_tile2: class extends self.ITiledBackgroundInstance {},
	CarBody2: class extends self.ISpriteInstance {},
	cash: class extends self.ISpriteInstance {},
	crash_block: class extends self.ISpriteInstance {},
	pole_warning: class extends self.I3DShapeInstance {},
	warning_sign: class extends self.ISpriteInstance {},
	block2: class extends self.I3DShapeInstance {},
	board_map2: class extends self.ITiledBackgroundInstance {},
	board_map1: class extends self.ITiledBackgroundInstance {},
	billboard_txt: class extends self.ISpriteFontInstance {},
	ground_top3: class extends self.ITiledBackgroundInstance {},
	billboard: class extends self.I3DShapeInstance {},
	pole_warning2: class extends self.I3DShapeInstance {},
	score_txt: class extends self.ISpriteFontInstance {},
	best_txt: class extends self.ISpriteFontInstance {},
	flip_txt: class extends self.ISpriteFontInstance {},
	money_ui2: class extends self.ISpriteInstance {},
	fuel_text: class extends self.ISpriteFontInstance {},
	landing_part1_map: class extends self.ISpriteInstance {},
	gas_info: class extends self.ISpriteInstance {},
	left_touch: class extends self.ISpriteInstance {},
	right_touch: class extends self.ISpriteInstance {},
	jump_touch: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	fullscreen: class extends self.ISpriteInstance {},
	block3: class extends self.I3DShapeInstance {},
	camera_control: class extends self.ITiledBackgroundInstance {},
	title: class extends self.ISpriteInstance {},
	syderstudio_logo: class extends self.ISpriteInstance {},
	billboard2: class extends self.I3DShapeInstance {},
	car_stopper: class extends self.ITiledBackgroundInstance {},
	right_key: class extends self.ISpriteInstance {},
	garage: class extends self.ISpriteInstance {},
	blocker_menu: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	rotate: class extends self.ISpriteInstance {},
	dummy2: class extends self.ITiledBackgroundInstance {},
	trigger2: class extends self.ISpriteInstance {},
	tut_touch: class extends self.ISpriteInstance {},
	Jump_info: class extends self.ISpriteInstance {},
	engine_upgrade: class extends self.ISpriteInstance {},
	block4: class extends self.I3DShapeInstance {},
	body_upgrade: class extends self.ISpriteInstance {},
	wheel_upgrade: class extends self.ISpriteInstance {},
	fuel_upgrade: class extends self.ISpriteInstance {},
	strength_upgrade: class extends self.ISpriteInstance {},
	garage_bg: class extends self.ISpriteInstance {},
	garage_ui_icon: class extends self.ISpriteInstance {},
	garage_title: class extends self.ISpriteInstance {},
	garage_item_info: class extends self.ISpriteInstance {},
	money_ui3: class extends self.ISpriteInstance {},
	money_txt_garage: class extends self.ISpriteFontInstance {},
	buy: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	missionArray: class extends self.IArrayInstance {},
	missionText: class extends self.ITextInstance {},
	missionStatus: class extends self.ITextInstance {},
	char1_body: class extends self.IWorldInstance {},
	char1_right_wheel: class extends self.IWorldInstance {},
	char1_left_wheel: class extends self.IWorldInstance {},
	char3_body: class extends self.IWorldInstance {},
	char3_left_wheel: class extends self.IWorldInstance {},
	char3_right_wheel: class extends self.IWorldInstance {},
	change_skin: class extends self.ISpriteInstance {},
	prev: class extends self.ISpriteInstance {},
	next: class extends self.ISpriteInstance {},
	menu_blocker: class extends self.I3DShapeInstance {},
	char4_right_wheel: class extends self.IWorldInstance {},
	char4_left_wheel: class extends self.IWorldInstance {},
	char4_body: class extends self.IWorldInstance {},
	char5_body: class extends self.IWorldInstance {},
	char5_right_wheel: class extends self.IWorldInstance {},
	char5_left_wheel: class extends self.IWorldInstance {},
	mission_bg: class extends self.ITiledBackgroundInstance {},
	mission_txt_UI: class extends self.ISpriteFontInstance {},
	check: class extends self.ISpriteInstance {},
	mission_txt_UI2: class extends self.ISpriteFontInstance {},
	money_ui4: class extends self.ISpriteInstance {},
	mission_complete: class extends self.ISpriteFontInstance {},
	char6_right_wheel: class extends self.IWorldInstance {},
	char6_body: class extends self.IWorldInstance {},
	char6_left_wheel: class extends self.IWorldInstance {},
	missionCompleteArray: class extends self.IArrayInstance {},
	pause: class extends self.ISpriteInstance {},
	pause_bg1: class extends self.ITiledBackgroundInstance {},
	pause_bg_a: class extends self.ISpriteInstance {},
	continue: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	about_txt: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	crashed_bg: class extends self.ISpriteInstance {},
	final_money: class extends self.ISpriteFontInstance {},
	garage_btn: class extends self.ISpriteInstance {},
	money_ui5: class extends self.ISpriteInstance {},
	score_txt_crashed: class extends self.ISpriteFontInstance {},
	pause_bg2: class extends self.ITiledBackgroundInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	about2: class extends self.ISpriteInstance {},
	char_body: class extends self.IWorldInstance {},
	garage_text: class extends self.ISpriteInstance {},
	garage_yellow_neon: class extends self.ISpriteInstance {},
	garage_blue_neon: class extends self.ISpriteInstance {},
	block6: class extends self.I3DShapeInstance {},
	garage_spark: class extends self.IParticlesInstance {},
	building3d: class extends self.IWorldInstance {},
	bg_black: class extends self.ITiledBackgroundInstance {},
	side_road_texture: class extends self.ISpriteInstance {},
	fps_counter: class extends self.ISpriteFontInstance {},
	vignetteanimation: class extends self.ISpriteInstance {},
	f_car: class extends self.IWorldInstance {},
	_3d_jet: class extends self.IWorldInstance {},
	jet_part: class extends self.IParticlesInstance {},
	stars_sky: class extends self.ITiledBackgroundInstance {},
	newspaper: class extends self.ISpriteInstance {},
	drone3d: class extends self.IWorldInstance {},
	block_side: class extends self.I3DShapeInstance {},
	billboard_txt_ins: class extends self.ISpriteFontInstance {},
	building_texture: class extends self.ISpriteInstance {},
	char7_body: class extends self.IWorldInstance {},
	char7_left_wheel: class extends self.IWorldInstance {},
	char7_right_wheel: class extends self.IWorldInstance {},
	char8_body: class extends self.IWorldInstance {},
	char8_left_wheel: class extends self.IWorldInstance {},
	char8_right_wheel: class extends self.IWorldInstance {},
	char11_body: class extends self.IWorldInstance {},
	char11_left_wheel: class extends self.IWorldInstance {},
	char11_right_wheel: class extends self.IWorldInstance {},
	char12_body: class extends self.IWorldInstance {},
	char12_left_wheel: class extends self.IWorldInstance {},
	char12_right_wheel: class extends self.IWorldInstance {},
	lock_unlock_btn: class extends self.ISpriteInstance {},
	VehicleCost: class extends self.ISpriteFontInstance {},
	jet_texture: class extends self.ISpriteInstance {},
	_3d_jet2: class extends self.IWorldInstance {},
	board_3d: class extends self.I3DShapeInstance {},
	pole4_map3: class extends self.ITiledBackgroundInstance {},
	car1_texture: class extends self.ISpriteInstance {},
	car2_texture: class extends self.ISpriteInstance {},
	car3_texture: class extends self.ISpriteInstance {},
	car4_texture: class extends self.ISpriteInstance {},
	car5_texture: class extends self.ISpriteInstance {},
	car6_texture: class extends self.ISpriteInstance {},
	car7_texture: class extends self.ISpriteInstance {},
	upgrade_json: class extends self.IJSONInstance {},
	car8_texture: class extends self.ISpriteInstance {},
	car9_texture: class extends self.ISpriteInstance {},
	fog_txt: class extends self.ISpriteInstance {},
	glow_btn: class extends self.ISpriteInstance {},
	fog_btn: class extends self.ISpriteInstance {},
	title2: class extends self.ISpriteInstance {},
	mission_bg_patch: class extends self.IWorldInstance {},
	attribution_txt: class extends self.ISpriteFontInstance {},
	resolution_txt: class extends self.ISpriteInstance {},
	resolution_btn: class extends self.ISpriteInstance {},
	info_op_txt: class extends self.ISpriteFontInstance {},
	tutorial_txt: class extends self.ISpriteFontInstance {},
	rotate_info: class extends self.ISpriteInstance {},
	bomb_gas: class extends self.IParticlesInstance {},
	control_enable: class extends self.ISpriteInstance {},
	GameDistributionSDK: class extends self.IInstance {},
	Family1: class extends self.ISpriteInstance {},
	wheel: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {},
	upgrades: class extends self.ISpriteInstance {},
	carBody3D: class extends self.IWorldInstance {},
	carWheel3D: class extends self.IWorldInstance {}
}